version: "3"

services:
  notion_google_calendar_sync:
    container_name: notion_google_calendar_sync
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
    environment:
      CRON_SCHEDULE: "${CRON_SCHEDULE}"
      KUMA_PUSH_URL: "${KUMA_PUSH_URL}"
    restart: unless-stopped
